name: Currency Converter Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    environment: test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Make environment
        uses: SpicyPizza/create-envfile@v1.3
        with:
          NODE_ENV: production
          API_VERSION: v1
          PORT: 8090
          EXCHANGE_RATE_ACCESS_KEY: 'zzzzxxxyyyy'

      - name: Install dependencies
        run: npm ci

      - name: Run all tests
        run: npm run test

  deploy:
    environment: production
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy main branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run production migration
        run: npm run prisma:deploy

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}


